# Generated by Django 5.1.6 on 2025-02-10 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('ward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
