# Generated by Django 5.1.6 on 2025-02-10 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
        ('ward', '0002_alter_ward_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='friend.friend'),
        ),
    ]
