# Generated by Django 5.1.6 on 2025-02-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0003_alter_ward_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='name',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
