# Generated by Django 5.1.6 on 2025-02-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0004_ward_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
