# Generated by Django 5.1.6 on 2025-02-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0005_alter_ward_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='user',
        ),
    ]
