# Generated by Django 5.1.6 on 2025-02-10 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Active', 'AT'), ('Completed', 'CO'), ('Canceled', 'CA'), ('Acepted', 'AC'), ('Rejected', 'RE'), ('Edited', 'ED'), ('Incompleted', 'IN'), ('Pending', 'PE')], default='Pending', max_length=20)),
                ('type', models.CharField(choices=[('FamilyHomeEvening', 'FHV'), ('Service', 'SE'), ('Ministering', 'MI'), ('Teaching', 'TA')], default='Teaching', max_length=20)),
                ('user', models.ManyToManyField(to='users.user')),
            ],
        ),
    ]
