# Generated by Django 5.1.6 on 2025-02-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='calling',
            field=models.CharField(choices=[('Bishop', 'B'), ('Member', 'M'), ('Elder', 'E'), ('QPresident', 'QP'), ('QCounselor', 'QC'), ('JWPresident', 'JWP'), ('JWCounselor', 'JWC'), ('RSPresident', 'RSP'), ('RSCounselor', 'RSC'), ('SPresident', 'SP'), ('SCounselor', 'SC'), ('HPriesthood', 'HP')], default='Member', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='memberId',
            field=models.CharField(max_length=11),
        ),
    ]
