# Generated by Django 5.1.6 on 2025-02-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_calling_alter_user_memberid'),
        ('ward', '0006_remove_ward_friend_remove_ward_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ward.ward'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default='https://static.vecteezy.com/system/resources/thumbnails/002/318/271/small/user-profile-icon-free-vector.jpg', max_length=255),
        ),
    ]
