# Generated by Django 5.1.6 on 2025-02-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='friend',
            field=models.ManyToManyField(blank=True, to='friend.friend'),
        ),
    ]
