# Generated by Django 5.1.6 on 2025-02-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
        ('ward', '0006_remove_ward_friend_remove_ward_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ward.ward'),
        ),
    ]
