# Generated by Django 5.1.6 on 2025-02-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_friend_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='lessons',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
