# Generated by Django 5.1.6 on 2025-02-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_alter_friend_lessons_alter_friend_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='lessons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
